FROM node:20 AS builder

WORKDIR /calcom

COPY package.json yarn.lock .yarnrc.yml turbo.json ./
COPY .yarn ./.yarn

COPY apps ./apps
COPY packages ./packages

RUN yarn install
RUN yarn workspace @calcom/api-v2 build


FROM node:20

WORKDIR /calcom

ENV NODE_ENV=production

COPY --from=builder /calcom/package.json ./
COPY --from=builder /calcom/yarn.lock ./
COPY --from=builder /calcom/.yarn ./.yarn
COPY --from=builder /calcom/node_modules ./node_modules

COPY --from=builder /calcom/apps ./apps
COPY --from=builder /calcom/packages ./packages

EXPOSE 3000

CMD ["yarn", "workspace", "@calcom/api-v2", "start:prod"]