FROM node:20-alpine AS deps

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    git \
    libc6-compat

RUN corepack enable

WORKDIR /calcom

COPY . .

ENV NODE_OPTIONS=--max_old_space_size=4096

RUN yarn install


FROM node:20-alpine AS builder

WORKDIR /calcom

COPY --from=deps /calcom ./

ENV NODE_ENV=development
ENV NODE_OPTIONS=--max_old_space_size=4096

RUN yarn turbo run build --filter=@calcom/api-v2...


FROM node:20-alpine AS runner

RUN apk add --no-cache libc6-compat

WORKDIR /calcom

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /calcom .

EXPOSE 3000

CMD ["node","apps/api/v2/dist/apps/api/v2/src/main.js"]